

defmodule Chrysopoeia.CSS.Benchmarks.Test do
  # Ensure that any bench marks return the results that we would expect

  use ExUnit.Case
  import SaneAsserts
  alias Chrysopoeia.Parser.ParseTree, as: ParseTree

  defp load_wikipedia_html() do
    {_, content} = File.read("./test/html_test_samples/parsing_wikipedia.html")

    content |> Chrysopoeia.Parser.Floki.parse
  end

  test "CSS find single element by id - wikipedia" do 
    result = load_wikipedia_html()
      |> ParseTree.find("[id=Psycholinguistics]")
      |> elem(1)
      |> assert_eq [accumulator: [{"span", [{"class", "mw-headline"}, {"id", "Psycholinguistics"}], ["Psycholinguistics"]}], index: 0]
  end

  # TODO : 1 this demonstrates the need to parse the result of a find into 
  #        find.
  #      : perfect test for psudo
  test "CSS find preceeding operatior - wikipedia" do
    result = load_wikipedia_html()
      |> ParseTree.find("h3 + p")
      |> elem(1)
      |> assert_eq [accumulator: [{"p", [],
              ["The traditional grammatical exercise of parsing, sometimes known as ", {"i", [], ["clause analysis"]},
               ",\n involves breaking down a text into its component parts of speech with \nan explanation of the form, function, and syntactic relationship of each\n part.",
               {"sup", [{"id", "cite_ref-3"}, {"class", "reference"}], [{"a", [{"href", "#cite_note-3"}], [{"span", [], ["["]}, "3", {"span", [], ["]"]}]}]}, " This is determined in large part from study of the language's ",
               {"a", [{"href", "http://en.wikipedia.org/wiki/Conjugation_%28grammar%29"}, {"title", "Conjugation (grammar)"}, {"class", "mw-redirect"}], ["conjugations"]}, " and ",
               {"a", [{"href", "http://en.wikipedia.org/wiki/Declensions"}, {"title", "Declensions"}, {"class", "mw-redirect"}], ["declensions"]},
               ",\n which can be quite intricate for heavily inflected languages. To parse a\n phrase such as 'man bites dog' involves nothing that the singular noun \n'man' is the subject of the sentence, the verb 'bites' is the third \nperson singular of the present tense of the verb 'to bite', and the \nsingular noun 'dog' is the object of the sentence. Techniques such as ",
               {"a", [{"href", "http://en.wikipedia.org/wiki/Sentence_diagram"}, {"title", "Sentence diagram"}], ["sentence diagrams"]}, " are sometimes used to indicate relation between elements in the sentence."]},
             {"p", [],
              ["In ", {"a", [{"href", "http://en.wikipedia.org/wiki/Psycholinguistics"}, {"title", "Psycholinguistics"}], ["psycholinguistics"]},
               ",\n parsing involves not just the assignment of words to categories, but \nthe evaluation of the meaning of a sentence according to the rules of \nsyntax drawn by inferences made from each word in the sentence. This \nnormally occurs as words are being heard or read. Consequently, \npsycholinguistic models of parsing are of necessity ",
               {"i", [], ["incremental"]},
               ", \nmeaning that they build up an interpretation as the sentence is being \nprocessed, which is normally expressed in terms of a partial syntactic \nstructure. Creation of the wrong structure can lead to the phenomenon \nknown as ",
               {"a", [{"href", "http://en.wikipedia.org/wiki/Garden_path_sentence"}, {"title", "Garden path sentence"}], ["garden-pathing"]}, "."]},
             {"p", [],
              ["A ", {"b", [], ["parser"]}, " is a software component that takes input data (frequently text) and builds a ",
               {"a", [{"href", "http://en.wikipedia.org/wiki/Data_structure"}, {"title", "Data structure"}], ["data structure"]}, " – often some kind of ",
               {"a", [{"href", "http://en.wikipedia.org/wiki/Parse_tree"}, {"title", "Parse tree"}], ["parse tree"]}, ", ",
               {"a", [{"href", "http://en.wikipedia.org/wiki/Abstract_syntax_tree"}, {"title", "Abstract syntax tree"}], ["abstract syntax tree"]},
               "\n or other hierarchical structure – giving a structural representation of\n the input, checking for correct syntax in the process. The parsing may \nbe preceded or followed by other steps, or these may be combined into a \nsingle step. The parser is often preceded by a separate ",
               {"a", [{"href", "http://en.wikipedia.org/wiki/Lexical_analysis"}, {"title", "Lexical analysis"}], ["lexical analyser"]},
               ", which creates tokens from the sequence of input characters; alternatively, these can be combined in ",
               {"a", [{"href", "http://en.wikipedia.org/wiki/Scannerless_parsing"}, {"title", "Scannerless parsing"}], ["scannerless parsing"]},
               ". Parsers may be programmed by hand or may be automatically or semi-automatically generated by a ",
               {"a", [{"href", "http://en.wikipedia.org/wiki/Parser_generator"}, {"title", "Parser generator"}, {"class", "mw-redirect"}], ["parser generator"]}, ". Parsing is complementary to ",
               {"a", [{"href", "http://en.wikipedia.org/wiki/Templating_language"}, {"title", "Templating language"}, {"class", "mw-redirect"}], ["templating"]}, ", which produces formatted ", {"i", [], ["output."]},
               " These may be applied to different domains, but often appear together, such as the ", {"a", [{"href", "http://en.wikipedia.org/wiki/Scanf"}, {"title", "Scanf"}, {"class", "mw-redirect"}], ["scanf"]}, "/",
               {"a", [{"href", "http://en.wikipedia.org/wiki/Printf"}, {"title", "Printf"}, {"class", "mw-redirect"}], ["printf"]}, " pair, or the input (front end parsing) and output (back end code generation) stages of a compiler."]},
             {"p", [], ["Some of the parsers that use ", {"a", [{"href", "http://en.wikipedia.org/wiki/Top-down_parsing"}, {"title", "Top-down parsing"}], ["top-down parsing"]}, " include:"]},
             {"p", [], ["Some of the parsers that use ", {"a", [{"href", "http://en.wikipedia.org/wiki/Bottom-up_parsing"}, {"title", "Bottom-up parsing"}], ["bottom-up parsing"]}, " include:"]},
             {"p", [],
              ["Some of the well known parser development tools include the following. Also see ",
               {"a", [{"href", "http://en.wikipedia.org/wiki/Comparison_of_parser_generators"}, {"title", "Comparison of parser generators"}], ["comparison of parser generators"]}, "."]}], index: 0]
  end
end



  
